Bank/Bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Bank/bankapp/urls.py
from . import views
from django.urls import path
from .views import BranchView, get_filtered_branches

app_name='bankapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('register', views.reg, name='reg'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('form', views.form, name='form'),
    path('new', views.simple, name='simple'),
    path('select-branch/', BranchView.as_view(), name='select_branch'),
    path('get-branches/', get_filtered_branches, name='get_filtered_branches'),
]

Bank/bankapp/models.py
from django.db import models

# Create your models here

class District(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Branch(models.Model):
    name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Bank/bankapp/forms.py
from django import forms
from .models import District,Branch

class MyForm(forms.Form):
    district = forms.ModelChoiceField(queryset=District.objects.all())
    branch = forms.ModelChoiceField(queryset=Branch.objects.all(),required=False)

class BranchForm(forms.Form):
    district = forms.ModelChoiceField(queryset=District.objects.all(), empty_label="Select District")
    branch = forms.ModelChoiceField(queryset=Branch.objects.none(), empty_label="Select Branch")

Bank/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View

from .forms import BranchForm
from .models import District,Branch


# Create your views here.
def index(request):
    return render(request,'Home.html')
def simple(request):
    return render(request,'new.html')

def login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/new')
        else:
            messages.info(request,"Invalid User")
            return redirect('/login')
    return render(request,"login.html")
def reg(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        cnf_password=request.POST['cnfpassword']
        if password==cnf_password:
            if User.objects.filter(username=username).exists():
                # this is to display on webpage "Already User exists"
                messages.info(request,"Already User exists")
                # goes to register page itself by giving urls.py name
                return redirect('/register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                messages.info(request, "Successfully Registered")
                # this would print the message on terminal
                print("User Created")
                # goes to home page
                return redirect('/login')
        else:
            messages.info(request, "Password does not match")
            print("Password does not match")
    return render(request,"register.html")

def form(request):
    form = BranchForm(request.GET)
    return render(request, 'form.html', {'form': form})

from django.http import JsonResponse
from .models import Branch

def get_filtered_branches(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id)
    branch_choices = [(branch.id, branch.name) for branch in branches]
    return JsonResponse({'branch_choices': branch_choices})

class BranchView(View):
    template_name = 'form.html'

    def get(self, request):
        form = BranchForm()
        messages.success(request, "Application Received")
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = BranchForm(request.POST)
        messages.success(request, "Application Received")
        return render(request, self.template_name, {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('/')

Bank/templates/Home.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row pt-4">
            <center><p style="font-family: Georgia, serif; font-size: 40px;">XYZ BANK</p></center>
        </div>
    </div>
        <ul>
          <li><a href="/login">Login</a></li>
          <li><a href="/register">Register</a></li>
          <li class="dropdown ">
            <a href="#">Branches</a>
                <div class="dropdown-content">
                  <a href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a>
                  <a href="https://en.wikipedia.org/wiki/Kannur">Kannur</a>
                  <a href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
                  <a href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a>
                  <a href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a>
                </div>
          </li>
        </ul>
    <div class="container-fluid">
        <img src="{% static 'img/banner.png' %}" alt="banner" height="500px" width="1497px">
    </div>
    <div class="container pt-4">
        <p>
            A bank is a cornerstone of the modern financial system, serving as a pivotal institution that provides a wide array of financial services to individuals, businesses, and governments. At its core, a bank is a financial intermediary, connecting those with surplus funds to those in need of capital. One of its primary functions is to accept and safeguard deposits, offering various types of accounts to cater to diverse financial needs. This secure storage of funds allows individuals and entities to transact and manage their money efficiently.

        In addition to deposit services, banks are vital in extending credit and loans, thereby fueling economic growth and development. They facilitate the acquisition of homes, the establishment of businesses, and the execution of various projects by lending funds and charging interest. Banks also play an integral role in payment processing, enabling the seamless transfer of money through electronic transfers, checks, and credit cards.

        Furthermore, banks often offer investment services, aiding customers in wealth management and capital growth. They provide access to a broad spectrum of financial products, including mutual funds, brokerage services, and advisory expertise. Lastly, while distinct from commercial banks, central banks possess the unique power to issue a nation's currency, ensuring the stability of the monetary system. Overall, banks are indispensable pillars of the global economy, underpinning financial stability and facilitating economic prosperity.
        </p>
    </div><br>
    <center>
      <a href="/login">Login</a>
    </center><br><br>
    <div class="container-fluid" style="background-color:#FFFFFF;">
        <center><p>@copyright;  XYZ Bank Pvt Ltd | All Rights Reserved</p></center>
    </div>
</body>
</html>

Bank/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .registration-container {
            width: 800px;
            margin: 100px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #E3E6E3;
        }


        .registration-container input[type="text"],
        .registration-container input[type="password"],
        .registration-container input[type="email"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

         .registration-container input[type="button"]{

            padding: 10px;
            margin-bottom: 10px;
            background-color: #00FE84;
            border: none;
            border-radius: 3px;
            color: #fff;
            cursor: pointer;
        }

        .registration-container input[type="submit"]{

            padding: 10px;
            margin-bottom: 10px;
            background-color: #007bff;
            border: none;
            border-radius: 3px;
            color: #fff;
            cursor: pointer;
        }

        .registration-container input[type="submit"]:hover {
            background-color: #0056b3;
        }

    </style>
</head>
<body>
<div class="registration-container">
    <h2 align="center" style="font-size:40px;">Form</h2>
    <div>
        <div>
            <form action="{% url 'bankapp:select_branch' %}" method="get">
                {% csrf_token %}
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required><br><br>

            <label for="dob">DOB:</label>
            <input type="date" id="dob" name="dob" required><br><br>

            <label for="age">Age:</label>
            <input type="number" id="age" name="age" required><br><br>

            <label for="gender">Gender:</label>
            <input type="radio" id="male" name="gender" value="male" required>
            <label for="male">Male</label>
            <input type="radio" id="female" name="gender" value="female" required>
            <label for="female">Female</label><br><br>

            <label for="phone">Phone Number:</label>
            <input type="tel" id="phone" name="phone" pattern="[0-9]{10}" required><br><br>

            <label for="email">Mail ID:</label>
            <input type="email" id="email" name="email" required><br><br>

            <label for="address">Address:</label>
            <textarea id="address" name="address" required></textarea><br><br>

             {{ form.district.label_tag }} {{ form.district }}
              {{ form.branch.label_tag }} {{ form.branch }}

            <br><br>
            <label for="account_type">Account Type:</label>
            <select id="account_type" name="account_type" required>
                <option value="savings">Savings Account</option>
                <option value="current">Current Account</option>
                <!-- Add more account types here -->
            </select><br><br>

            <label>Materials Provided:</label><br>
            <input type="checkbox" id="debit-card" name="materials[]" value="debit-card">
            <label for="debit-card">Debit Card</label><br>
            <input type="checkbox" id="credit-card" name="materials[]" value="credit-card">
            <label for="credit-card">Credit Card</label><br>
            <input type="checkbox" id="cheque-book" name="materials[]" value="cheque-book">
            <label for="cheque-book">Cheque Book</label><br><br>

            <center>
                <input type="submit" value="Submit" class="btn btn-primary">
                <a href="{% url 'bankapp:logout' %}" class="btn btn-danger">Logout</a><br>
                {% for msg in messages %}
                    {{msg}}<br>
                    <a href="/">Home Page</a>
                {% endfor %}
            </center>

            </form><br><br>
        </div>

    </div>

</div>
</body>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      const districtDropdown = document.querySelector('#id_district');
      const branchDropdown = document.querySelector('#id_branch');

      districtDropdown.addEventListener('change', function() {
        const selectedDistrict = districtDropdown.value;
        fetch(`/get-branches/?district_id=${selectedDistrict}`)
          .then(response => response.json())
          .then(data => {
            branchDropdown.innerHTML = '';
            data.branch_choices.forEach(branch => {
              branchDropdown.options.add(new Option(branch[1], branch[0]));
            });
          });
      });
    });
</script>
</html>

Bank/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .login-container {
            width: 300px;
            margin: 100px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #A5A6A5;
        }

        .login-container label {
            display: block;
            margin-bottom: 5px;
        }

        .login-container input[type="text"],
        .login-container input[type="password"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .login-container input[type="submit"] {
            width: 100%;
            padding: 10px;
            font-size: 15px;
            background-color: #007bff;
            border: none;
            border-radius: 3px;
            color: #fff;
            cursor: pointer;
        }

        .login-container input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
<div class="login-container">
        <h2 align="center">Login</h2>
        <form action="login" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <input type="submit" value="LOGIN"><br><br>
            <center><a href="/register" style="font-size: 20px">Register</a></center>
        </form><br><br>
    {% for msg in messages %}
        {{msg}}
    {% endfor %}
    </div>
</body>
</html>

Bank/templates/new.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;">
  <div class="container-fluid">
      <a class="navbar-brand" href="#" style="font-family: Georgia, serif;">XYZ BANK</a>
  </div>
</nav>

<div class="container mb-3 mt-3">
    <div>
        <p>
           A bank is a cornerstone of the modern financial system, serving as a pivotal institution that provides a wide array of financial services to individuals, businesses, and governments. At its core, a bank is a financial intermediary, connecting those with surplus funds to those in need of capital. One of its primary functions is to accept and safeguard deposits, offering various types of accounts to cater to diverse financial needs. This secure storage of funds allows individuals and entities to transact and manage their money efficiently.

    In addition to deposit services, banks are vital in extending credit and loans, thereby fueling economic growth and development.
        </p>
    </div>
</div>

<div class="container pt-4 mt-5">
    <center>
        <a href="/form" class="btn btn-primary">Fill the Form</a>
        <a href="/" class="btn btn-danger">Home</a>
    </center>
</div>


</body>
</html>

Bank/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .registration-container {
            width: 300px;
            margin: 100px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #E3E6E3;
        }

        .registration-container label {
            display: block;
            margin-bottom: 5px;
        }

        .registration-container input[type="text"],
        .registration-container input[type="password"],
        .registration-container input[type="email"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .registration-container input[type="submit"] {
            width: 100%;
            padding: 10px;
            font-size: 15px;
            background-color: #007bff;
            border: none;
            border-radius: 3px;
            color: #fff;
            cursor: pointer;
        }

        .registration-container input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
<div class="registration-container">
    <h2 align="center">Registration</h2>
    <div class="row ">
        <div>
            <form action="register" method="post">
                {% csrf_token %}
                <div>
                    <input type="text" name="username" placeholder="Enter The Username" required>
                </div>
                <div>
                    <input type="password" name="password" placeholder="Enter Your Password" required>
                </div>
                <div>
                    <input type="password" name="cnfpassword" placeholder="Confirm The Password" required>
                </div>
                <div>
                    <input type="submit" value="SUBMIT">
                </div>
            </form><br><br>
            {% for msg in messages %}
                {{msg}}
            {% endfor %}
        </div>

    </div>

</div>
</body>
</html>